Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100  
  LogSavePath: storage/logs
  LoggerFileName: app_logger
  ZapperFileName: app_zapper
  LogFileExt: .log  
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

Database:
  DBType: postgres
  Username: ${USERNAME}
  Password:  ${DB_PASSWORD}
  Host: 127.0.0.1
  Port: ${PORT}
  DBName: miao
  TablePrefix: miao_
  SSLmode: disable
  TimeZone: Asia/Shanghai
  MaxIdleConns: 10  
  MaxOpenConns: 30 

JWT:
  Secret: ${SECRET}
  Issuer: ${ISSUER}
  Expire: 7200
