Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100  # 每页100条记录
  LogSavePath: storage/logs
  LoggerFileName: app_logger
  ZapperFileName: app_zapper
  LogFileExt: .log  # 扩展名

Database:
  DBType: postgres
  Username: postgres  
  Password:   
  Host: 127.0.0.1
  Port: 5432
  DBName: miao
  TablePrefix: miao_
  SSLmode: disable
  TimeZone: Asia/Shanghai
  MaxIdleConns: 10  # 空闲连接数
  MaxOpenConns: 30  # 打开连接数